name: GH-ACTION-REMOVE-AND-IGNORE
branding:
  icon: trash-2
  color: red
description: Remove file or directory from repository and ignore it in future commits.
inputs:
  git-user-email:
    description: Git user.email to use.
    default: 41898282+github-actions[bot]@users.noreply.github.com
  git-user-name:
    description: Git user.name.
    default: github-actions[bot]
  path-remove:
    description: Path to remove.    
    required: true
runs:
  using: composite
  steps:
    - shell: sh
      run: |
        git config user.name ${GIT_USER_NAME}
        git config user.email ${GIT_USER_EMAIL}
        sh "${{ github.action_path }}/index.sh"
      env:
        GIT_USER_NAME: ${{ inputs.git-user-name }}
        GIT_USER_EMAIL: ${{ inputs.git-user-email }}
        PATH_REMOVE: ${{ inputs.path-remove }}